Djangoproj/PurNet/PurNet/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin

from qa import views
from django.conf.urls import url, include
from django.contrib.auth.models import User
from qa.models import Question, Tag
from rest_framework import routers, serializers, viewsets
import course_mang

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

class QuestionSerializer(serializers.HyperlinkedModelSerializer):
    tags = serializers.SlugRelatedField(
        many=True,
        read_only=True,
        slug_field='slug'
     )
    class Meta:
        model = Question
        fields = ('id', 'pub_date', 'question_text', 'tags', 'views')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'api/users', UserViewSet)
router.register(r'api/questions', QuestionViewSet)

    
urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'PurNet.views.index'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^signup/$', 'authy.views.signup', name='signup'),
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset', {'post_reset_redirect' : '/user/password/reset/done/'},name="password_reset"),
    url(r'^user/password/reset/done/$','django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/user/password/done/'}),
    url(r'^user/password/done/$', 'django.contrib.auth.views.password_reset_complete'),
    url(r'^change/password/$','reset.views.change_password', name='changepassword'),
    #url(r'^', include('brainstorm.urls')), 
    #url(r'^mang_acct/', include('mang_acct.urls')),
    #url(r'^course_mang/', include('course_mang.urls')),
    #url(r'^create_acct/', include('create_acct.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^inbox/', include('inbox.urls')),
    #url(r'^pass_mang/', include('pass_mang.urls')),
    #url(r'^qa_forums/', include('qa_forums.urls')),
    #url(r'^rate_prof/', include('rate_prof.urls')),
    #url(r'^reset/', include('reset.urls')),
    #url(r'^user_homepage/', include('user_homepage.urls')),
    url(r'^$', 'PurNet.views.login', name='login'),
    url(r'^logout/', 'PurNet.views.logout', name='logout'),
    #url(r'^admin/', include(admin.site.urls)),
    
    url(r'^courses/', 'course_mang.views.list', name='courses_list'),
    url(r'^coursedetail/', 'course_mang.views.detail', name='courses_detail'),

    url(r'^groups/', 'group_mang.views.list', name='group_list'),
    url(r'^groupdetail/(?P<group_id>\d+)/$', 'group_mang.views.detail', name='group_detail'),


    url(r'^question/$', views.index, name='index'),
    url(r'^q/(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^answer/(?P<question_id>\d+)/$', views.answer, name='answer'),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^add/$', views.add, name='add'),
    url(r'^answer/$', views.add_answer, name='add_answer'),
    url(r'^vote/(?P<user_id>\d+)/(?P<answer_id>\d+)/(?P<question_id>\d+)/(?P<op_code>\d+)/$', views.vote, name='vote'),
    url(r'^comment/(?P<answer_id>\d+)/$', views.comment, name='comment'),
    url(r'^search/$', views.search, name='search'),
    url(r'^tag/(?P<tag>\w+)/$', views.tag, name='tag'),
    url(r'^thumb/(?P<user_id>\d+)/(?P<question_id>\d+)/(?P<op_code>\d+)/$', views.thumb, name='thumb'),

    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='profile'),
    #url(r'^register/$', views.register, name='register'),
    #url(r'^login/$', views.user_login, name='login'),
    #url(r'^logout/$', views.user_logout, name='logout'),

    url('^markdown/', include( 'django_markdown.urls')),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

                       
)

Djangoproj/PurNet/inbox/urls.py
from django.conf.urls import patterns, include, url

urlpatterns =[
    url(r'^$', 'inbox.views.inbox', name="inbox"),
    url(r'^sended/$', 'inbox.views.sended', name="sended"),
    url(r'^trash/$', 'inbox.views.trash', name="trash"),
    url(r'^compose/$', 'inbox.views.compose', name="compose"),
]

Djangoproj/PurNet/login/urls.py
from django.conf.urls import patterns, include, url

urlpatterns =[
    url(r'^signin', 'login.views.login', name="login"),
    url(r'^signout', 'login.views.logout', name="logout"),
]

Djangoproj/PurNet/login/models.py
from django.db import models

# Create your models here.

Djangoproj/PurNet/qa/models.py
from django.db import models

class Tag(models.Model):
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.slug

    class Meta:
        ordering = ('slug',)

from django.contrib.auth.models import User

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    points = models.IntegerField(default=0)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='qa/static/profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

from django_markdown.models import MarkdownField

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    tags = models.ManyToManyField(Tag)
    reward = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    user_data = models.ForeignKey(UserProfile)
    closed = models.BooleanField(default=False)

    def __str__(self):
        return self.question_text

class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = MarkdownField()
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    user_data = models.ForeignKey(UserProfile)
    def __str__(self):
        return self.answer_text

class Voter(models.Model):
    user = models.ForeignKey(UserProfile)
    answer = models.ForeignKey(Answer)

class QVoter(models.Model):
    user = models.ForeignKey(UserProfile)
    question = models.ForeignKey(Question)

class Comment(models.Model):
    answer = models.ForeignKey(Answer)
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    user_data = models.ForeignKey(UserProfile)
    def __str__(self):
        return self.comment_text

Djangoproj/PurNet/qa/forms.py
from qa.models import *
from django.contrib.auth.models import User
from django import forms

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text', 'tags')
        
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

Djangoproj/PurNet/login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as login_user
from django.contrib.auth.forms import AuthenticationForm
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect
from django.contrib.auth import logout as logout_user

def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect("/")
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login_user(request, user)
                return HttpResponseRedirect("/")
    else:
        form = AuthenticationForm()

    return TemplateResponse(request, 'login/login.html', {'form': form})

def logout(request):
    logout_user(request)
    return HttpResponseRedirect("/login/signin")

Djangoproj/PurNet/qa/templates/qa/add.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="container">

  {% include "qa/header.html" %}

  {% if message %}
  <strong>Enter a valid Question!</strong>
  {% endif %}

  {% if user.is_authenticated %}

  <form id="add_q" method="post" action="/add/">
    {% csrf_token %}
    <input class="input-lg" style="width:100%" placeholder="Enter your question....." type="text" name="question"/> <br/><br/>

    <input class="input-lg" style="width:100%" placeholder="Enter tags separates by comma!" type="text" name="tags"/> <br/><br/>
    <input type="hidden" value="{{ user.id }}" name="user" />
    <input class="btn pull-right btn-success" type="submit" value="Submit Question" />
  </form>
  <p>Note. Question cannot be empty!</p>
  {% else %}
  <small><a href="/login">Please Login to Add Questions!</a></small>
  {% endif %}

</div>
{% include "qa/footer.html" %}

Djangoproj/PurNet/qa/templates/qa/answer.html
{% load django_markdown %}

<div class="container">

  {% include "qa/header.html" %}

{% if message %}
<strong>Enter a valid Answer!</strong>
{% endif %}
<h4>Answering Question : {{ question.question_text }}</h4>

{% if user.is_authenticated %}
<form id="answer" method="post" action="/answer/">
  {% csrf_token %}
  <textarea id="ans" rows="7" style="width:100%" placeholder="Enter your Answer....." type="text" name="answer"></textarea>
  {% markdown_editor "#ans" %}
  {% markdown_media %}
   <br/><br/>
  <input type="hidden" value="{{ question.id }}" name="question" />
  <input type="hidden" value="{{ user.id }}" name="user" />
  <input class="btn btn-success" type="submit" value="Submit Answer" />
</form>
{% else %}
<small><a href="/login">Please Login to Add Questions!</a></small>
{% endif %}
</div>

{% include "qa/footer.html" %}

Djangoproj/PurNet/qa/templates/qa/comment.html
<div class="container">

  {% include "qa/header.html" %}

  {% if message %}
  <strong>Enter a valid comment!</strong>
  {% endif %}

  {% if user.is_authenticated %}

  <form id="add_q" method="post" action="/comment/{{ answer_id }}/">
    {% csrf_token %}
    <input class="input-lg" style="width:100%" placeholder="Enter your comment....." type="text" name="comment"/> <br/><br/>
    <input type="hidden" value="{{ user.id }}" name="user" />
    <input class="btn pull-right btn-success" type="submit" value="Submit Comment" />
  </form>
  <p>Note. Comment cannot be empty!</p>
  {% else %}
  <small><a href="/login">Please Login to Add comment!</a></small>
  {% endif %}

</div>

{% include "qa/footer.html" %}

Djangoproj/PurNet/qa/templates/qa/detail.html
<style>
.closed {
  width:100%;
  height:7px;
  position: absolute;

  background: #FF4444;
}

.open {
  width:100%;
  height:7px;
  position: absolute;

  background: #99CC00;
}

.rewarding {
  width:100%;
  height:7px;
  position: absolute;

  background: #AA66CC;
}
</style>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
<style>
big {
  font-size:20px;
  padding : 2px 0px 2px 0px;
}
</style>
{% load staticfiles %}
{% load django_markdown %}

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

<style>
cool {
  font-family: 'Lobster', cursive;
}
</style>

{% if question.reward %}
  <div class="rewarding"></div>
{% else %}
{% if question.closed %}
  <div class="closed"></div>
{% else %}
  <div class="open"></div>
{% endif %}
{% endif %}

<div class="container">

  {% include "qa/header.html" %}

{% if message %}
<div class="alert alert-danger" role="alert">{{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
</div>
{% endif %}

{% if question.reward %}
<div class="alert alert-info" role="alert">This question has been marked to be worth a reward of <b>{{ question.reward }}<b> points!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
</div>
{% endif %}

<div class="jumbotron">
  <small class="pull-right">Posted by {{ question.user_data.user.username }}, {{ question.pub_date }}</small>
  <h3><cool>Q: </cool>{{ question.question_text }}</h3>
  <p>
    {% if user.is_authenticated %}
  <a href="/thumb/{{ user.id }}/{{ question.id }}/0/" class="btn btn-success"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a>
  <a href="/thumb/{{ user.id }}/{{ question.id }}/1/" class="btn btn-danger"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span></a>
    {% endif %}
    {% if question.closed %}
    <p class="pull-right">This Question has been closed.</p>
    {% else %}
    <a class="btn btn-primary btn-sm pull-right" href="/answer/{{ question.id }}" role="button">Answer this Question!</a>
    {% endif %}
  </p>
</div>

{% if answers %}
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Answers</h3>
  </div>
  <div class="panel-body">
    {% for answer in answers %}
    <div class="row">
      {% if user.is_authenticated %}
      <div class ="col-md-1">
        <div class="row">
          <div class ="col-sm-1"><big class="pull-left"><b>{{ answer.votes }}</b></big></div>
          <div class ="col-sm-1"><a class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer" href="/vote/{{ user.id }}/{{ answer.id }}/{{ question.id }}/0/"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a> <a class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer" href="/vote/{{ user.id }}/{{ answer.id }}/{{ question.id }}/1/"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a></div>
        </div>
      </div>
      {% endif %}
      <div class ="col-md-9">
        <a href="/comment/{{ answer.id }}/" class="pull-right"><small><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comment &nbsp;</small></a>

        {% if answer.votes > 0 %}
        <div id="ans" class="alert alert-info" role="alert">{{ answer.answer_text|markdown }}</div>
        {% elif answer.votes == 0 %}
        <div id="ans" class="alert alert-warning" role="alert">{{ answer.answer_text|markdown }}</div>
        {% else %}
        <div id="ans" class="alert alert-danger" role="alert">{{ answer.answer_text|markdown }}</div>
        {% endif %}

          {% for comment in answer.comment_set.all %}
          <p>-<b>{{ comment.comment_text }}</b><small>, <a href="/profile/{{ comment.user_data.user.id }}">{{ comment.user_data.user.username }}</a> at {{ comment.pub_date }}</small></p>
          {% endfor %}
      </div>
      <div class ="col-md-2">

        {% if answer.user_data.picture %}
        <img class="pull-right" src="{{ answer.user_data.picture }}">
        {% else %}
        <img class="pull-right" width="50px" height="50px" src="{% static "qa/user.png" %}">
        {% endif %}

        <p class="pull-right">- <b><a href="/profile/{{ answer.user_data.user.id }}">{{ answer.user_data.user.username }}</a> ({{ answer.user_data.points }})</b></p>
      </div>
    </div>

    {% endfor %}
  </div>
</div>

<div class="pagination">
  <span class="step-links">
    {% if answers.has_previous %}
    <a href="?page={{ answers.previous_page_number }}">< Previous | </a>
    {% endif %}

    <span class="current">
      Page {{ answers.number }} of {{ answers.paginator.num_pages }}.
    </span>

    {% if answers.has_next %}
    <a href="?page={{ answers.next_page_number }}"> | Next ></a>
    {% endif %}
  </span>
</div>

{% else %}
<img class="pull-right" src="{% static "qa/question.jpg" %}" alt="question"/>
<center><h2>This question is still open, <a href="/answer/{{ question.id }}" role="button">Write answer!</a></h2></center>
{% endif %}

</div>
{% include "qa/footer.html" %}

Djangoproj/PurNet/qa/templates/qa/footer.html
<hr>

 <br/><br/>

 <div id="search">
   <button type="button" class="close">×</button>
   <form method="post" action="/search/">
     {% csrf_token %}
     <input type="search" value="" name="word" placeholder="type keyword(s) here" />
     <input class="btn btn-lg btn-warning" type="submit" value="Find" />
   </form>
 </div>

<style>
code {
    font-family: Monaco, Consolas, "Andale Mono", "DejaVu Sans Mono", monospace;
    font-size: 95%;
    line-height: 140%;
    white-space: pre;
    white-space: pre-wrap;
    white-space: -moz-pre-wrap;
    white-space: -o-pre-wrap;
    background: #faf8f0;
}

#content code {
    display: block;
    padding: 0.5em 1em;
    border: 1px solid #bebab0;
}
</style>

 <!-- Modal -->
 <div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="APIModal" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span> API Access</h4>
       </div>
       <div class="modal-body">
         <ul>
           <li>
             <b>List of Questions</b>
             <br/>Retrieve the list of questions.
             <br/>json URL : <code>http://djangoqa.azurewebsites.net/api/questions/?format=json</code>
           </li>
           <br/>
           <li>
             <b>List of Users</b>
             <br/>Retrieve the list of users.
             <br/>json URL : <code>http://djangoqa.azurewebsites.net/api/users/?format=json</code>
           </li>
          <ul>
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
       </div>
     </div>
   </div>
 </div>

Djangoproj/PurNet/qa/templates/qa/index.html
<style>
.topbar {
  width:100%;
  height:7px;
  position: absolute;
  z-index:1000;

  background: #FF8800;
}
</style>

<div class="topbar"></div>

<div class="container">

{% include "qa/header.html" %}

<div class="col-md-8">

  <ul class="nav nav-tabs nav-justified">
    <li role="presentation" class="active"><a href="#latest" aria-controls="latest" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Latest</a></li>
    <li role="presentation"><a href="#unans" aria-controls="unans" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> Unanswered <span class="badge">{{ noans.count }}</span></a></li>
    <li role="presentation"><a href="#reward" aria-controls="reward" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Most Rewarding <span class="badge">{{ reward.count }}</span></a></li>
  </ul>
  <br/>


<div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="latest">
{% if questions %}
  {% for question in questions %}
  <div class="row">
  <div class="col-sm-1 ans"><small><div class="ques">{{ question.answer_set.count }}</div>Answers</small></div>
  <div class="col-sm-1 ans"><small><div class="ques">{{ question.views }}</div>Views</small></div>
  <p>
    {% if question.reward %}<span class="glyphicon glyphicon-fire" aria-hidden="true"></span>{% endif %} <a class="ques" href="/q/{{ question.id }}/">{{ question.question_text }}</a>
    <br/>
    {% for tag in question.tags.all %}
    <a href="/tag/{{ tag.slug|slugify }}/"><tag>{{ tag.slug }}</tag></a>
    {% endfor %}
    <small> {{ question.pub_date}}</small>
  </p>
</div>
<hr>
  {% endfor %}

<div class="pagination">
  <span class="step-links">
    {% if questions.has_previous %}
    <a href="?page={{ questions.previous_page_number }}">< Previous | </a>
    {% endif %}

    <span class="current">
      Page {{ questions.number }} of {{ questions.paginator.num_pages }}.
    </span>

    {% if questions.has_next %}
    <a href="?page={{ questions.next_page_number }}"> | Next ></a>
    {% endif %}
  </span>
</div>

{% else %}
<div class="alert alert-warning" role="alert">No Questions are available!</div>
{% endif %}
</div>

<div role="tabpanel" class="tab-pane" id="unans">
{% if noans %}
  {% for question in noans %}
  <div class="row">
  <div class="col-sm-1 ans"><small><div class="ques">{{ question.answer_set.count }}</div>Answers</small></div>
  <div class="col-sm-1 ans"><small><div class="ques">{{ question.views }}</div>Views</small></div>
  <p>
    {% if question.answer_set.count %}<span class="glyphicon glyphicon-fire" aria-hidden="true"></span>{% endif %} <a class="ques" href="/q/{{ question.id }}/">{{ question.question_text }}</a>
    <br/>
    {% for tag in question.tags.all %}
    <a href="/tag/{{ tag.slug|slugify }}/"><tag>{{ tag.slug }}</tag></a>
    {% endfor %}
    <small> {{ question.pub_date}}</small>
  </p>
</div>
<hr>
  {% endfor %}

{% else %}
<div class="alert alert-warning" role="alert">No Questions are available!</div>
{% endif %}
</div>

<div role="tabpanel" class="tab-pane" id="reward">
{% if reward %}
  {% for question in reward %}
  <div class="row">
  <div class="col-sm-1 ans"><small><div class="ques">{{ question.answer_set.count }}</div>Answers</small></div>
  <div class="col-sm-1 ans"><small><div class="ques">{{ question.views }}</div>Views</small></div>
  <p>
    {% if question.answer_set.count %}<span class="glyphicon glyphicon-fire" aria-hidden="true"></span>{% endif %} <a class="ques" href="/q/{{ question.id }}/">{{ question.question_text }}</a>
    <br/>
    <reward>Earn <b>{{ question.reward }}</b> points</reward>
    {% for tag in question.tags.all %}
    <a href="/tag/{{ tag.slug|slugify }}/"><tag>{{ tag.slug }}</tag></a>
    {% endfor %}
    <small> {{ question.pub_date}}</small>
  </p>
</div>
<hr>
  {% endfor %}

{% else %}
<div class="alert alert-warning" role="alert">No Questions are available!</div>
{% endif %}
</div>

  </div>
</div>

<div class="col-md-4">

  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Total Questions: {{ totalcount }}</h4>
      <h4>Total Answers: {{ anscount }}</h4>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><span class="glyphicon glyphicon-tag" aria-hidden="true"></span> Recent Tags</h3>
    </div>
    <div class="panel-body">
      {% for question in questions %}
      {% for tag in question.tags.all %}
      <a href="/tag/{{ tag.slug|slugify }}/"><tag>{{ tag.slug }}</tag></a>
      {% endfor %}
      {% endfor %}
    </div>
  </div>

  {% if noans.count %}
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title">Unanswered Questions</h3>
    </div>
    <div class="panel-body">
    <ul>
      {% for question in noans %}
      <li><a href="/q/{{ question.id }}/">{{ question.question_text }}</a></li>
      {% endfor %}
    </ul>
    </div>
  </div>
  {% endif %}

  {% if user.is_authenticated %}

  <div class="span3 well">
    <center>
      <a href="/" data-toggle="modal"><img src="/static/qa/user.png" name="aboutme" width="100" height="100" class="img-circle"></a>
      <h3>{{ user.first_name }} {{ user.last_name }}</h3>
      <a href="/">Home Page</a> |
      <a href="/logout/">Logout</a>
    </center>
  </div>
  {% else %}
  <a class="btn btn-block btn-success" href="/login"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Login | Sign Up</a><br/>
  {% endif %}

</div>
</div>
{% include "qa/footer.html" %}

Djangoproj/PurNet/qa/templates/qa/profile.html
<div class="container">

  {% include "qa/header.html" %}

<h2 class="pull-right">Points: {{ user.points }}</h1>
<ul>
  <li><b>Website :</b> {{ user.website }} </li>
   <li><b>e-mail :</b> {{ user.user.email }} </li>
   <li><b>Date Joined :</b> {{ user.user.date_joined }} </li>
   <li><b>Last Login :</b> {{ user.user.last_login }} </li>
   <li><b>is Active :</b> {{ user.user.is_active }} </li>
<ul>

</div>

{% include "qa/footer.html" %}

Djangoproj/PurNet/qa/templates/qa/register.html
<div class="container">

  {% include "qa/header.html" %}

  {% if registered %}
  <strong>thank you for registering!</strong>
  <a href="/">Return to the homepage.</a><br />
  {% else %}
  <strong>Enter the following details:</strong><br /><br />

  <form id="user_form" method="post" action="/register/"
  enctype="multipart/form-data">

  {% csrf_token %}

  <!-- Display each form. The as_p method wraps each element in a paragraph
  (<p>) element. This ensures each element appears on a new line,
  making everything look neater. -->
  {{ user_form.as_p }}
  {{ profile_form.as_p }}

  <!-- Provide a button to click to submit the form. -->
  <input type="submit" name="submit" value="Register" />
</form>
{% endif %}

</div>

{% include "qa/footer.html" %}